
version: '2'

volumes:
 mongodb_data:

networks:
  core_network:
    #enable_ipv6: true
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.23.0/24
          gateway: 192.168.23.1

services:

  nrf:
    image: open5gs/ubuntu-bionic-open5gs-build:latest
    # depends_on:
    #   - amf
    container_name: nrf
    hostname: nrf
    # ports:
    #   - "7777:7777"
    #   - "7777:7777/udp"
    # expose:
    #   - "7777"
    #   - "7777/udp"
    entrypoint:
      - "/bin/sh"
      - "/etc/open5gs/run_nrf.sh"
    volumes:
      - "./:/etc/open5gs"
      - "./log:/home/open5gs/install/var/log/open5gs"
    networks:
      core_network:
        ipv4_address: 192.168.23.10

  # mongodb:
  #   image: mongo:latest
  #   container_name: "mongodb"
  #   volumes:
  #     - mongodb_data:/data/db
  #   hostname: mongodb
  #   networks:
  #     core_network:
  #       ipv4_address: 192.168.23.50

  # webui:
  #   image: open5gs/open5gs-webui:latest
  #   depends_on:
  #     - mongodb
  #   environment:
  #     - DB_URI=mongodb://mongodb/open5gs
  #   container_name: webui
  #   hostname: webui
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #       - "./:/etc/open5gs"
  #   entrypoint:
  #     - "/bin/sh"
  #     - "/etc/open5gs/run_webui.sh"
  #   networks:
  #     core_network:
  #       ipv4_address: 192.168.23.6

  # mongodbloader:
  #   image: mongo:latest
  #   depends_on:
  #     - webui
  #   environment:
  #     - DB_HOST=mongodb
  #   volumes:
  #     - "./provisioning/db/run_db.sh:/tmp/run.sh"
  #     - "./provisioning/db/imsi1.json:/tmp/imsi1.json"
  #   entrypoint:
  #     - /bin/sh
  #     - /tmp/run.sh
  #   networks:
  #     core_network:
  #       ipv4_address: 192.168.23.19

  # udr:
  #   image: open5gs/ubuntu-bionic-open5gs-build:latest
  #   depends_on:
  #     - mongodb
  #   container_name: udr
  #   hostname: udr
  #   # ports:
  #   #   - "7777:7777"
  #   #   - "7777:7777/udp"
  #   # expose:
  #   #   - "7777"
  #   #   - "7777/udp"
  #   entrypoint:
  #     - "/bin/sh"
  #     - "/etc/open5gs/run_udr.sh"
  #   volumes:
  #     - "./:/etc/open5gs"
  #     - "./log:/home/open5gs/install/var/log/open5gs"
  #   networks:
  #     core_network:
  #       ipv4_address: 192.168.23.13

  # udm:
  #   image: open5gs/ubuntu-bionic-open5gs-build:latest
  #   depends_on:
  #     - udr
  #   container_name: udm
  #   hostname: udm
  #   # ports:
  #   #   - "7777:7777"
  #   #   - "7777:7777/udp"
  #   # expose:
  #   #   - "7777"
  #   #   - "7777/udp"
  #   entrypoint:
  #     - "/bin/sh"
  #     - "/etc/open5gs/run_udm.sh"
  #   volumes:
  #     - "./:/etc/open5gs"
  #     - "./log:/home/open5gs/install/var/log/open5gs"
  #   networks:
  #     core_network:
  #       ipv4_address: 192.168.23.12

  # ausf:
  #   image: open5gs/ubuntu-bionic-open5gs-build:latest
  #   depends_on:
  #     - smf
  #   container_name: ausf
  #   hostname: ausf
  #   # ports:
  #   #   - "7777:7777"
  #   #   - "7777:7777/udp"
  #   # expose:
  #   #   - "7777"
  #   #   - "7777/udp"
  #   entrypoint:
  #     - "/bin/sh"
  #     - "/etc/open5gs/run_ausf.sh"
  #   volumes:
  #     - "./:/etc/open5gs"
  #     - "./log:/home/open5gs/install/var/log/open5gs"
  #   networks:
  #     core_network:
  #       ipv4_address: 192.168.23.11

  # amf:
  #   image: open5gs/ubuntu-bionic-open5gs-build:latest
  #   depends_on:
  #     - mongodb
  #   container_name: amf
  #   hostname: amf
  #   # ports:
  #   #   - "7777:7777"
  #   #   - "7777:7777/udp"
  #   # expose:
  #   #   - "7777"
  #   #   - "7777/udp"
  #   entrypoint:
  #     - "/bin/sh"
  #     - "/etc/open5gs/run_amf.sh"
  #   volumes:
  #     - "./:/etc/open5gs"
  #     - "./log:/home/open5gs/install/var/log/open5gs"
  #   networks:
  #     core_network:
  #       ipv4_address: 192.168.23.5

  # smf:
  #   image: open5gs/ubuntu-bionic-open5gs-build:latest
  #   depends_on:
  #     - amf
  #   container_name: smf
  #   hostname: smf
  #   # ports:
  #   #   - "7777:7777"
  #   #   - "7777:7777/udp"
  #   # expose:
  #   #   - "7777"
  #   #   - "7777/udp"
  #   entrypoint:
  #     - "/bin/sh"
  #     - "/etc/open5gs/run_smf.sh"
  #   volumes:
  #     - "./:/etc/open5gs"
  #     - "./log:/home/open5gs/install/var/log/open5gs"
  #   networks:
  #     core_network:
  #       ipv4_address: 192.168.23.4


  # hss:
  #   image: open5gs/ubuntu-bionic-open5gs-build:latest
  #   depends_on:
  #     - mongodb
  #   container_name: hss
  #   hostname: hss
  #   entrypoint:
  #     - "/bin/sh"
  #     - "/etc/open5gs/run_hss.sh"
  #   volumes:
  #     - "./config:/etc/open5gs"
  #     - "./log/hss:/home/open5gs/install/var/log/open5gs"
  #   networks:
  #     core_network:
  #       ipv4_address: 192.168.23.10

  # mme:
  #    image: open5gs/ubuntu-bionic-open5gs-build:latest
  #    depends_on:
  #      - hss
  #    container_name: mme
  #    hostname: mme
  #    entrypoint:
  #     - "/bin/sh"
  #     - "/etc/open5gs/run_mme.sh"
  #    ports:
  #     - "36412:36412"
  #     - "36412:36412/udp"
  #    expose:
  #     - "2123"
  #     - "2123/udp"
  #    volumes:
  #     - "./config:/etc/open5gs"
  #     - "./log/mme:/home/open5gs/install/var/log/open5gs"
  #    networks:
  #      core_network:
  #        ipv4_address: 192.168.23.20

  # sgw:
  #    image: open5gs/ubuntu-bionic-open5gs-build:latest
  #    container_name: sgw
  #    hostname: sgw
  #    entrypoint:
  #     - "/bin/sh"
  #     - "/etc/open5gs/run_sgw.sh"
  #    volumes:
  #     - "./config:/etc/open5gs"
  #     - "./log/sgw:/home/open5gs/install/var/log/open5gs"
  #    ports:
  #      - "2152:2152"
  #      - "2152:2152/udp"
  #      - "2123:2123"
  #      - "2123:2123/udp"
  #    networks:
  #      core_network:
  #        ipv4_address: 192.168.23.30

  # pgw:
  #    build: ./pgw
  #    container_name: pgw
  #    hostname: pgw
  #    entrypoint:
  #     - "/bin/sh"
  #     - "/etc/open5gs/run_pgw.sh"
  #    volumes:
  #     - "./config:/etc/open5gs"
  #     - "./log/pgw:/home/open5gs/install/var/log/open5gs"
  #    expose:
  #     - "2123"
  #     - "2123/udp"
  #     - "2152"
  #     - "2152/udp"
  #    cap_add:
  #      -  NET_ADMIN
  #    devices:
  #      -  /dev/net/tun
  #    privileged: true # if IPv6 enabled
  #    networks:
  #      core_network:
  #        ipv4_address: 192.168.23.40

  # pcrf:
  #   image: open5gs/ubuntu-bionic-open5gs-build:latest
  #   depends_on:
  #      - mongodb
  #      - hss
  #   container_name: pcrf
  #   hostname: pcrf
  #   entrypoint:
  #     - "/bin/sh"
  #     - "/etc/open5gs/run_pcrf.sh"
  #   volumes:
  #     - "./config:/etc/open5gs"
  #     - "./log/pcrf:/home/open5gs/install/var/log/open5gs"
  #   networks:
  #      core_network:
  #        ipv4_address: 192.168.23.9
